### ISSUE TITLE
.git/refs/heads/main - No such file or directory

### ISSUE THREAD

**Issue by dehlirious** [Ahwxorg/LibreY#107]
At this [file](https://github.com/Ahwxorg/LibreY/blob/main/misc/footer.php), 

`$hash = file_get_contents(".git/refs/heads/main");`
is present, but if you [download](https://codeload.github.com/Ahwxorg/LibreY/zip/refs/heads/main) the Git, it doesn't exist. 

If you `git clone https://github.com/Ahwxorg/LibreY.git` , it does.

My suggestion: either do
```
if (file_exists($filename)) {
    $hash = file_get_contents(".git/refs/heads/main");
} 
```
or get latest commit via
```
https://api.github.com/repos/Ahwxorg/LibreY/git/refs/heads/main
```

**Comment by Ahwxorg** [comment]
> or get latest commit via
> 
> https://api.github.com/repos/Ahwxorg/LibreY/git/refs/heads/main

That wont work since we have GitHub rate limiting issues, since those pages get a lot of views each day/hour/time.

With that being said, I'll commit that to `main`, since that seems like a solid fix for now.

I advice against using the download, though. This is because, since LibreY does not really make use of releases, the version people run is often outdated. Easiest way to update it, is to make a cronjob that automatically pulls the newest information.

**Comment by dehlirious** [comment]
> > or get latest commit via
> > https://api.github.com/repos/Ahwxorg/LibreY/git/refs/heads/main
> 
> That wont work since we have GitHub rate limiting issues, since those pages get a lot of views each day/hour/time.
> 
> With that being said, I'll commit that to `main`, since that seems like a solid fix for now.
> 
> I advice against using the download, though. This is because, since LibreY does not really make use of releases, the version people run is often outdated. Easiest way to update it, is to make a cronjob that automatically pulls the newest information.

That makes sense, I'd wonder if cacheing would be a solution then, e.g. only grabbing latest commit once a day or every few days.

Also I didn't intend to post this, I wasn't finished! But after word of that issue, it makes no difference now. 

Not sure what's currently used but this example uses curl, but with caching in mind it would have to be a bit different
```
$ch = curl_init('https://api.github.com/repos/Ahwxorg/LibreY/commits/main');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    'User-Agent: YourApp', // Cannot be blank
]);
$response = curl_exec($ch);
curl_close($ch);
$commitInfo = json_decode($response, true);
if ($commitInfo === null) {
    echo 'N/A';//error
    exit;
}
print_r( $commitInfo['commit']['tree']['url']);
```

Don't forget, with 
```
$file = ".git/refs/heads/main";
if (file_exists($file)) {
	$hash = file_get_contents($file);
}
```
to add
```
else{ $hash = "N/A"; }
```

**Comment by Ahwxorg** [comment]
[Done](https://github.com/Ahwxorg/LibreY/commit/2ab1768bce0e8884ea55d110355cb04e08be856b)

**Comment by Ahwxorg** [comment]
> > > or get latest commit via
> > > https://api.github.com/repos/Ahwxorg/LibreY/git/refs/heads/main
> > 
> > 
> > That wont work since we have GitHub rate limiting issues, since those pages get a lot of views each day/hour/time.
> > With that being said, I'll commit that to `main`, since that seems like a solid fix for now.
> > I advice against using the download, though. This is because, since LibreY does not really make use of releases, the version people run is often outdated. Easiest way to update it, is to make a cronjob that automatically pulls the newest information.
> 
> That makes sense, I'd wonder if cacheing would be a solution then, e.g. only grabbing latest commit once a day or every few days.
> 
> Also I didn't intend to post this, I wasn't finished! But after word of that issue, it makes no difference now.
> 
> Not sure what's currently used but this example uses curl, but with caching in mind it would have to be a bit different
> 
> ```
> $ch = curl_init('https://api.github.com/repos/Ahwxorg/LibreY/commits/main');
> curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
> curl_setopt($ch, CURLOPT_HTTPHEADER, [
>     'User-Agent: YourApp', // Cannot be blank
> ]);
> $response = curl_exec($ch);
> curl_close($ch);
> $commitInfo = json_decode($response, true);
> if ($commitInfo === null) {
>     echo 'N/A';//error
>     exit;
> }
> print_r( $commitInfo['commit']['tree']['url']);
> ```
> 
> Don't forget, with
> 
> ```
> $file = ".git/refs/heads/main";
> if (file_exists($file)) {
> 	$hash = file_get_contents($file);
> }
> ```
> 
> to add
> 
> ```
> else{ $hash = "N/A"; }
> ```

Wait no, nevermind, I was being stupid. That does not show the latest commit, but the commit the instance is on. It should get fetched from the file locally. If we were to fetch from GitHub, my point from earlier is still valid.

**Comment by Ahwxorg** [comment]
I know, but when you go to an instance, it should show the commit that the instance runs on.

**Comment by dehlirious** [comment]
> I know, but when you go to an instance, it should show the commit that the instance runs on.

I realized that right after I commented, accurate!

**Comment by davidovski** [comment]
Yeah, it doesn't really make sense to get the latest commit from the main branch, since the commit that we are interested in is the one that the current instance is running (maybe this should be re-labeled as "current commit"?)

adding `else{ $hash = "N/A"; }` is a good idea though, since on instances that arent running from the source tree won't have any commit data to display, so will show a misleading "Latest commit:" message on the instance. Perhaps this message could be removed entirely if no commit could be found?

One solution would be keeping a file somewhere in the tree called "version" and to remember to manually update it every time there is a change, however I'm not sure if this is really necessary with the state of things.
