### ISSUE TITLE
Basic customization?

### ISSUE THREAD

**Issue by FinallyCanuck** [Ahwxorg/LibreY#138]
Using this in a docker container and was surprised by the lack of a config file for things like CSS, logos, footer text. Does something like this already exist?

**Comment by codedipper** [comment]
Most of the stuff you can already change is mostly for the functionality of LibreY, not so much the visual stuff. This is because if we add a configopt to change literally everything in the project, the code will become a mess. You might also notice that most of the code runs on pure PHP files, and can't really just be replaced by a string in a config file. Since the code is open source and Docker is cool, you can just change everything to your liking. You have a few solutions:

1. [A default theme configopt is being implemented slowly](https://github.com/Ahwxorg/LibreY/issues/135). You can still change your theme through `/settings.php` if you store cookies in your browser.
2. Most if not all of the images are located at `/favicon.ico` and `/static/images/`, create a patch for that and build the image.
3. Footer text can be modified at `/misc/footer.php`, create a patch for that and build the image.

**Comment by FinallyCanuck** [comment]
Thank you for the details. I’ll give it a go.

**Comment by codedipper** [comment]
Another thing; LibreY is licensed under the GNU Affero General Public License v3.0, which is similar to the regular GPLv3, but your changes must be stated and made open source.
Thank you! <3
