### ISSUE TITLE
504 Gateway Timeout Issue with nginx

### ISSUE THREAD

**Issue by Retro-Hax** [Ahwxorg/LibreY#15]
As the Title implies im getting a Gateway timeout issue (which only happens sometimes weirdly enough) now switching back from librey to librex does not give me this issue at all same config everything so it is very confusing as to why that happens so if someone could get me an explanation and a potential fix thatd be amazing

also the instance link is still the same https://librex.retro-hax.net

**Comment by Retro-Hax** [comment]
Alos decided to add this Issue which i know happens to a lot of Instances of LibreX/Y but it is very annoying and inconvinient so thats also something i wanted to ask as to why that happens 
![image](https://github.com/Ahwxorg/LibreY/assets/69952967/00ae42aa-fa3b-4709-8c4d-6cf97d2053dd)

**Comment by davidovski** [comment]
The reason why sometimes a libreX/Y instance doesn't show any results and fails to even show the footer is usually because it encountered an error getting results from google.com, usually due to a rate limit. 

The main issue is with the instance fallback feature (PR #1) which, upon failing to get a result from google.com, will fallback to a different libreX instance via that instance's API. What I believe to be the issue is that this process is taking far too long to complete, causing a gateway timeout, likely due to the fallback instances also trying to fallback to other instances. (potentially a loop is happening where the instance falls back to another instance, which falls back to the original instance and so on...) 

For a temporary fix, you can set `instance_fallback` to `false` in your config, however your instance will likely still be ratelimited by google and not be able to get any results from your instance. 

I will investigate the issue further and hopefully create a PR fixing the issues as soon as possible.

**Comment by Ahwxorg** [comment]
I changed the default setting of instance_fallback to false to avoid other issues for now.

See commit [5f8bc14d73aea2e137b99997cd35894d7f8d3d8c](https://github.com/Ahwxorg/LibreY/commit/5f8bc14d73aea2e137b99997cd35894d7f8d3d8c)

**Comment by Ahwxorg** [comment]
Reopening since the issues seems to persist

**Comment by davidovski** [comment]
It seems as if all of the instances are being ratelimited or at the very least sending empty responses. Thats probably why fallback requests are taking so long. The PR I'm working on (#16) should stop any endless loops when doing a fallback request, however still working on a solution to avoid ratelimiting on the instance itself.
