### ISSUE TITLE
Instances in README

### ISSUE THREAD

**Issue by davidovski** [Ahwxorg/LibreY#40]
There are some instances listed in instances.json that aren't listed in README.md. Perhaps the list of instances in `README.md` should be removed since each instance will have its own list of instances generated from `instances.json` in `instances.php`. Having instances listed in one place should be much easier to manage.

**Comment by codedipper** [comment]
Otherwise people won't know where to find a list of instances. Sure, there's `instances.json` but nobody's going to go and read that because it's scary code language.
I left it there because since we're basically the maintainers of the project, we *know* when a new commit comes out, and therefore the instance list on our instances is updated.

**Comment by davidovski** [comment]
Maybe its worth replacing the section with a link to a generated instance list, ie: [search.ahwx.org/instances.php](https://search.ahwx.org/instances.php) though that instance that is hosting the linked instance list needs to be online as much as possible.

**Comment by codedipper** [comment]
Buddy I'm the only one that doesn't have downtime.
https://librex.me/instances.php
https://librex.revvy.de/instances.php
hxxp://librex[.]revvybrr6pvbx4n3j4475h4ghw4elqr4t5xo2vtd3gfpu2nrsnhh57id[.]onion/instances.php
hxxp://revekebotog64xrrammtsmjwtwlg3vqyzwdurzt2pu6botg4bejq[.]b32[.]i2p/instances.php
