### ISSUE TITLE
Auto updating?

### ISSUE THREAD

**Issue by PardesiCat** [Ahwxorg/LibreY#52]
It looks like LibreY is getting updates from time to time.

But the real question is, do we have to build some script or method to update the files for librey hosts' instance owners?

Otherwise, time-to-time updates will be painful.because Liby receives frequent updates.

espeacially non-dockers users

**Comment by davidovski** [comment]
Personally, I believe that libreY itself shouldnt be responsible for keeping itself up to date in anyway, since that could potentially be a security issue, not to mention that this would require phoning "home" to regularly check if there are any updates, which is probably not behaviour that we want by default. Though, feel free to disagree.

Hypothetically, it would be ideal if the system's package manager is used for this purpose. It's already being used to keep other software up to date, so libreY can be updated through those means. Of course, this would require packaging libreY for your distro (and any others). It will require quite a lot of work, but with enough maintainers it is probably the best way to keep instances up to date. To some extent this is already being done through the docker build scripts via a github workflow that then pushes it to ghcr.io automatically, so adding workflows to build packages for other distros could work.

Alternatively, you could opt for a more DIY approach and writing a small script yourself to automate the process. I currently have a script that does this for libreY and a few other sites that I host from a git repository. Its something along the lines of this:

```sh
#!/bin/sh

cd /path/to/your/librey
while true; do
    git pull
    sleep 25
done
```

this script is then run via a systemd service that will keep it up to date with `main` or whichever branch that repository is checked out to. I've been running a script like this for a while and it does the trick, so let me know if u have any success.

**Comment by PardesiCat** [comment]
Hi, I saw the script, but this script is not ideal for updating because there are also config files (so using a script with a system is a bad idea). I suggest adding a little more code to the script, like backup confs or backup files, then updating. This will not be so hard.
and here we don't have to pack in package manager format. The update.sh script will perform better than the package manager.
I asked because the update timing gap is smaller and gets updated in a short time, and there is no sign or indicator available that indicates that a new update is available.
+ insead of fork repo, it will be great if there is another sandalone repo (where give creadit to librex owner) so people won't get confused. (example: searx + searxng)

**Comment by codedipper** [comment]
> Personally, I believe that libreY itself shouldnt be responsible for keeping itself up to date in anyway, since that could potentially be a security issue, not to mention that this would require phoning "home" to regularly check if there are any updates, which is probably not behaviour that we want by default. Though, feel free to disagree.
> 
> Hypothetically, it would be ideal if the system's package manager is used for this purpose. It's already being used to keep other software up to date, so libreY can be updated through those means. Of course, this would require packaging libreY for your distro (and any others). It will require quite a lot of work, but with enough maintainers it is probably the best way to keep instances up to date. To some extent this is already being done through the docker build scripts via a github workflow that then pushes it to ghcr.io automatically, so adding workflows to build packages for other distros could work.
> 
> Alternatively, you could opt for a more DIY approach and writing a small script yourself to automate the process. I currently have a script that does this for libreY and a few other sites that I host from a git repository. Its something along the lines of this:
> 
> ```shell
> #!/bin/sh
> 
> cd /path/to/your/librey
> while true; do
>     git pull
>     sleep 25
> done
> ```
> 
> this script is then run via a systemd service that will keep it up to date with `main` or whichever branch that repository is checked out to. I've been running a script like this for a while and it does the trick, so let me know if u have any success.

Just use `while sleep 25; do`

**Comment by acidvegas** [comment]
Bleeding edge updates straight from git are a bad idea & can be catastrophic. I would suggest we could incorperate PHP code to pull the latest "release" from this repository, and have it show in misc/footer.php so everyone running an instance can see if there is a latest version.

**Comment by Ahwxorg** [comment]
I personally don't think LibreY should update itself. If there's an important update (i.e. a vuln), we will notify in our Matrix room (#librey:ahwx.org), and you can update it yourself.

Am open for build scripts for packages, but I feel like - since we're depending on PHP and NGINX (or any other http server of choice) - that would also come with a lot of interference with other packages.

We could (pinging @davidovski here since it seems like they've done this already) possibly make a guide on how to do something like this yourself.

> Hi, I saw the script, but this script is not ideal for updating because there are also config files (so using a script with a system is a bad idea). I suggest adding a little more code to the script, like backup confs or backup files, then updating. This will not be so hard.

Then feel free to modify it yourself :).

> insead of fork repo, it will be great if there is another sandalone repo (where give creadit to librex owner) so people won't get confused. (example: searx + searxng)

What do you mean? We give full credit to @hnhx and the name is indeed different and a play on LibreX so I don't see the problem?

**Comment by PardesiCat** [comment]
> What do you mean? We give full credit to @hnhx and the name is indeed different and a play on LibreX so I don't see the problem?

 i mean  insead of direct fork  create separate repo for LibreY   (not fork) and another logo is possible 
then that git  you can credit ( libreX )   this will be goes into users suggestion + more eyecatching  +  less confuse for some peoples

>  we will notify in our Matrix room (#librey:ahwx.org), and you can update it yourself.

not there  in  like i mean   example he says  a alert in footer will be more good :)

**Comment by Ahwxorg** [comment]
> this will be goes into users suggestion

Don't know how the GitHub algorithm works, don't care to be honest.

> less confuse for some peoples

What?

> not there in like i mean example he says a alert in footer will be more good :)

Hmmmmm, we're gonna show hackers what instances are vulnerable... Also, how will you do this without phoning home?

**Comment by PardesiCat** [comment]
> Hmmmmm, we're gonna show hackers what instances are vulnerable... Also, how will you do this without phoning home?

libreY update available or not


> how will you do this without phoning home?

what do you mean ?

**Comment by Ahwxorg** [comment]
> libreY update available or not

Can you make a normal english sentence I can read?

> > how will you do this without phoning home?
> what do you mean ?

How do you want to make such a feature without having the LibreY PHP script make a request to GitHub (or any other server for that matter)? Would not even be possible because you're getting a GitHub rate limit after only ~25 tries iirc.

**Comment by PardesiCat** [comment]
Hello, I am not a programmer and have no knowledge of PHP codes.


am saying, "Some days ago, I got an invitation from Revvy to checkout the libreY project.

But when I came, I noticed the LibreY project was getting updates frequently, so I am not saying do it; I am giving suggestions. Is it possible to add an alert like this? When a new update is available on the home page, this kind of alert will be very helpful."

![ssaa](https://github.com/Ahwxorg/LibreY/assets/55957190/58bda419-ff2e-43a7-9050-e42b16815cee)

**Comment by Ahwxorg** [comment]
I don't want to give possible hackers a way to know what version of LibreY a system runs. Closing this as not planned.

**Comment by davidovski** [comment]
Just want to make a comment that the "latest commit" still shows, so any bad actor can still see the version that is running. However i think that this should still be visible, because although this means that its easier to see which instances are outdated with a vuln, people can decide to not use an outdated instance if they choose to. 
Hiding this information in any way is merely just security through obscurity: the vulnerability from previous updates would still exist on an non-updated instance, whether this is displayed or not.

**Comment by davidovski** [comment]
> Hi, I saw the script, but this script is not ideal for updating because there are also config files (so using a script with a system is a bad idea).
This script works on my machine perfectly fine, since `config.php` and `opensearch.xml` are not added to the git repo, so they dont get overwritten with upstream changes. However if for any reason it doesn't work like that for you, try doing a 
`git stash` before the pull, and then a `git stash pop` afterwards. Hope that helped.

**Comment by Ahwxorg** [comment]
> Just want to make a comment that the "latest commit" still shows, so any bad actor can still see the version that is running. However i think that this should still be visible, because although this means that its easier to see which instances are outdated with a vuln, people can decide to not use an outdated instance if they choose to. Hiding this information in any way is merely just security through obscurity: the vulnerability from previous updates would still exist on an non-updated instance, whether this is displayed or not.

Fair.
