### ISSUE TITLE
Cannot add as search provider in Firefox 

### ISSUE THREAD

**Issue by deansallinen** [Ahwxorg/LibreY#61]
Right-clicking on the URL bar should allow the user to add LibreY as an open search provider. 

Instead, we get an error message: `Firefox could not download the search plugin from: https://search.example.com/opensearch.xml?method=POST` where example.com is the correct domain where Librey is hosted.

Removing `method=POST` from header.php fixes the error message. 

Tested in Firefox 117 and 118.

**Comment by Ahwxorg** [comment]
I have had no issues adding LibreY as a search engine within Firefox, could you provide a screenshot of the issue?

**Comment by davidovski** [comment]
This is an issue with opensearch.xml not being configured correctly, make sure that you've copied `opensearch.xml.example` to `opensearch.xml` and edited the urls within it to point to your instance. I don't think we should be removing `method=POST` since that is used to tell the browser which HTTP method should be used, though I'm not sure if firefox respects this or not.

Are you using nginx or some other webserver? This could be an issue with how that webserver parses urls or something similar.

**Comment by Ahwxorg** [comment]
No problem! Kindly reach out if you have any other issues :).

**Comment by davidovski** [comment]
If you figure out what the problem was, feel free to post the solution here, might be helpful for others to know

**Comment by c6c534e825f4a3d41ede3e67473187d1** [comment]
Here's a better way of doing that:
1. Go to `about:config`
2. Add a new pref called `browser.urlbar.update2.engineAliasRefresh`, and set it to `true`
3. Go to your search settings (`about:preferences#search`)
4. You should be able to see a `Add` button on the bottom right corner, which allows you to add any url as search engine.

Taken from [here](https://superuser.com/questions/7327/how-to-add-a-custom-search-engine-to-firefox/1756774#1756774)
