### ISSUE TITLE
Implement captchas for better handling of spam

### ISSUE THREAD

**Issue by d4f5409d** [Ahwxorg/LibreY#78]
https://github.com/hnhx/captcha could be helpful.

**Comment by Ahwxorg** [comment]
I am not a huge fan of capcha's, but without JS they're *fine* but still very frustrating. After adding #1, #19 and #34 I honestly don't have a lot of issues on my personal instance.

How would you like to implement this?

**Comment by davidovski** [comment]
This might be a good idea if an instance is being spammed, to slow down users. However adding this extra step of user interaction will potentially break the api, since automated requests will need user interaction. Its a double edged-sword: we want to have an api that can be used to make automated requests (ie for instance fallback etc), but on the other hand this is where most of the spam to instances come through. 

I think testing if the request has been made by a human might not be the right solution to this problem, since most likely requests wont be. Features like results caching help filter out the amount of spam towards Google which are made by repeated requests, so it might be worth looking into how better to reduce the amount of requests towards Google made by spammy requests to LibreY. 

Perhaps LibreY could ratelimit requests that all quickly originated from the same source, however I don' t think that this should be something that LibreY needs to implement, since using something like nginx as a reverse proxy could be configured to have this functionality. 

While I'm not a fan of captchas, it might be worth implementing it as an "opt-in" (from the instance hoster's side), though again, should LibreY be responsible for filtering the requests made to itself or should it just trust whatever requests that it was given to be filtered out by nginx (or similar) already? 

Since most of the spam comes from requests to `/api.php` we could implement a config option to disable the api, though this wouldnt be very good since other instances won't be able to fallback on that instance, reducing the effectiveness of fallback in general. 

If you are getting spammed a lot, particularly with the same requests, try see if you can implement a ratelimit of sorts via nginx or something similar. Also take a look at tweaking the `cache_time` and `request_cooldown` config options, to change how long results are stored for and how long to timeout failing fallback requests respectively.

**Comment by d4f5409d** [comment]
> I am not a huge fan of capcha's, but without JS they're *fine* but still very frustrating. After adding #1, #19 and #34 I honestly don't have a lot of issues on my personal instance.
> 
> How would you like to implement this?

I just want to have something because librex.me has been shut down recently due to spam. Tor is not affected, only clearweb.

**Comment by Ahwxorg** [comment]
This is currently not planned, but a good PR is always welcome.

**Comment by Ahwxorg** [comment]
Closing this as #84 somewhat solves this problem, although it seems to be fine with #1 on most instances anyway...
